apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicyBinding
metadata:
  name: @@@SERVICEACCOUNT@@@-@@@NAMESPACE@@@-bind
  namespace: @@@NAMESPACE@@@
spec:
  policies: ["@@@POLICY@@@"]
  serviceAccountNames: ["@@@SERVICEACCOUNT@@@"]
  serviceAccountNamespaces: ["@@@NAMESPACE@@@"]
  #serviceAccountNames: ["vault-ro","vault-ro2"]
  #serviceAccountNamespaces: ["@@@NAMESPACE@@@","demo"]
  TTL: "1000"
  maxTTL: "2000"
  Period: "1000"
