kind: Pod
apiVersion: v1
metadata:
  name: vault-${APP}-test
spec:
  serviceAccountName: vault-${APP}
  initContainers:
    - name: vault-init
      image: everpeace/curl-jq
      command:
        - "sh"
        - "-c"
        - >
          KUBE_TOKEN=\$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
          curl -ks --request POST --data '{"jwt": "\$KUBE_TOKEN", "role": "$SVC_ACC"}' ${VAULTSERVER}/v1/auth/kubernetes/login | jq -j '.auth.client_token' > /etc/vault/token;
          X_VAULT_TOKEN=\$(cat /etc/vault/token);
          curl -ks --header "X-Vault-Token: \$X_VAULT_TOKEN" ${VAULTSERVER}/v1/secret/$SECRETPATH/${APP}/registry > /etc/app/registry;
      volumeMounts:
        - name: app-creds
          mountPath: /etc/app
        - name: vault-token
          mountPath: /etc/vault
  containers:
  - name: vault-manager
    image: everpeace/curl-jq
    command:
      - "sh"
      - "-c"
      - >
        X_VAULT_TOKEN=$(cat /etc/vault/token);
        VAULT_LEASE_ID=$(cat /etc/app/creds.json | jq -j '.lease_id');
        while true; do
          curl -ks --request PUT --header "X-Vault-Token: $X_VAULT_TOKEN" --data '{"lease_id": "'"$VAULT_LEASE_ID"'", "increment": 3600}' ${VAULTSERVER}/v1/sys/leases/renew;
          sleep 3600;
        done
    volumeMounts:
    - mountPath: /etc/vault
      name: vault-token
    - name: app-creds
      mountPath: /etc/app
  serviceAccountName: vault-${APP}
  volumes:
  - name: vault-token
    emptyDir: {}
    #alt_way projected:
    #alt_way   sources:
    #alt_way   - serviceAccountToken:
    #alt_way       path: vault-token
    #alt_way       expirationSeconds: 7200
    #alt_way       audience: vault
  - name: app-creds
    emptyDir: {}
