all:
  children:
    ansiblemaster:
      hosts:
        localhost:
          ansible_connection:    local
          ansible_master: True
          #ansible_port:   22
          #ansible_python_interpreter: /usr/bin/python3
      vars:
        kubeconfigfile: /home/dev/git/keys/api-token/k8s/config.{{ project }}
