---
kind: Pod
apiVersion: v1
metadata:
  name: vault-${APP}-test
spec:
  serviceAccountName: vault-${APP}
  initContainers:
    - name: vault-init
      image: everpeace/curl-jq
      command:
        - \"sh\"
        - \"-c\"
        - >
          KUBE_TOKEN=\$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
          curl --request POST --data '{\"jwt\": \"\$KUBE_TOKEN\", \"role\": \"$SVC_ACC\"}' ${VAULTSERVER}/v1/auth/kubernetes/login | jq -j '.auth.client_token' > /etc/vault/token;
          X_VAULT_TOKEN=\$(cat /etc/vault/token);
          curl --header \"X-Vault-Token: \$X_VAULT_TOKEN\" ${VAULTSERVER}/v1/secret/$SECRETPATH/${APP}/registry > /etc/app/registry;
      volumeMounts:
        - name: app-creds
          mountPath: /etc/app
        - name: vault-token
          mountPath: /etc/vault
  containers:
  - image: vault
    name: vault
    command:
      - \"cat\"
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
    - name: app-creds
      mountPath: /etc/app
  serviceAccountName: vault-${APP}
  volumes:
  - name: vault-token
    emptyDir: {}
    #alt_way projected:
    #alt_way   sources:
    #alt_way   - serviceAccountToken:
    #alt_way       path: vault-token
    #alt_way       expirationSeconds: 7200
    #alt_way       audience: vault
  - name: app-creds
    emptyDir: {}
