apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: vault-ro
  namespace:@@@NAMESPACE@@@
spec:
  vaultAppRef:
    name: vault
    namespace: @@NAMESPACE@@@
  policy: |
    path "@@@SECRETPATH@@@/*" {
      capabilities = ["read", "list"]
    }
